Repository MonkyMars/PWS, pull requests merged in 2025-09, with the labels that each got.

#4 Create workflow documentation for codebase management
  WORKFLOW.md
Labels: documentation, setup

#6 Fix formatting in README.md
  apps/server/README.md
Labels: documentation

#16 Format code using gofmt -w .
  apps/server/api/response/error.go
  apps/server/api/response/lib.go
  apps/server/api/response/success.go
  apps/ui/.prettierignore
  apps/ui/.prettierrc
  apps/ui/README.md
  apps/ui/app/app.css
  apps/ui/app/components/auth/login-form.tsx
  apps/ui/app/components/auth/register-form.tsx
  apps/ui/app/components/auth/validation.ts
  apps/ui/app/components/dashboard/dashboard.tsx
  apps/ui/app/components/dashboard/quick-actions.tsx
  apps/ui/app/components/dashboard/recent-activity.tsx
  apps/ui/app/components/dashboard/subject-card.tsx
  apps/ui/app/components/files/file-viewer.tsx
  apps/ui/app/components/footer.tsx
  apps/ui/app/components/index.ts
  apps/ui/app/components/navigation.tsx
  apps/ui/app/components/subjects/subject-detail.tsx
  apps/ui/app/components/ui/button.tsx
  apps/ui/app/components/ui/input.tsx
  apps/ui/app/hooks/index.ts
  apps/ui/app/hooks/use-auth.ts
  apps/ui/app/hooks/use-subjects.ts
  apps/ui/app/lib/README.md
  apps/ui/app/lib/api-client.ts
  apps/ui/app/lib/query-client.ts
  apps/ui/app/root.tsx
  apps/ui/app/routes.ts
  apps/ui/app/routes/dashboard.tsx
  apps/ui/app/routes/home.tsx
  apps/ui/app/routes/login.tsx
  apps/ui/app/routes/register.tsx
  apps/ui/app/routes/subjects.$subjectId.tsx
  apps/ui/app/types/README.md
  apps/ui/app/types/api.ts
  apps/ui/app/types/auth.ts
  apps/ui/app/types/index.ts
  apps/ui/app/types/subject.ts
  apps/ui/package.json
  apps/ui/react-router.config.ts
  apps/ui/tsconfig.json
  apps/ui/vite.config.ts
Labels: go/fiber, maintenance

#8 Added new database health route with metrics and type
  apps/server/api/internal/app.go
  apps/server/api/routes/app.go
  apps/server/types/app.go
Labels: enhancement, go/fiber

#15 Create .github/dependabot.yml for updates
  .github/dependabot.yml
Labels: enhancement, setup, maintenance

#14 Docker setup
  apps/server/.dockerignore
  apps/server/Dockerfile
  apps/server/api/middleware/cors.go
  apps/server/docker-compose.yml
  apps/ui/.dockerignore
  apps/ui/Dockerfile
  apps/ui/app/lib/api-client.ts
Labels: enhancement, react/ui, go/fiber, maintenance

#10 Include bun installation step in README
  README.md
Labels: documentation

#19 Update workflow instructions with git pull guidance
  WORKFLOW.md
Labels: documentation

#20 Unused/file
  apps/server/main.go
  apps/server/services/database.go
  apps/server/services/pg.go
Labels: go/fiber, maintenance

#22 Revise README for configuration and health check updates
  README.md
Labels: documentation

#23 Rename WORKFLOW.md to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#25 Fix padding size for home page hero
  apps/ui/app/routes/home.tsx
Labels: react/ui

#26 Add feature flags for logging in and registering
  apps/ui/.env.example
  apps/ui/app/components/feature-disabled.tsx
  apps/ui/app/components/navigation.tsx
  apps/ui/app/env.d.ts
  apps/ui/app/hooks/use-auth.ts
  apps/ui/app/lib/api-client.ts
  apps/ui/app/lib/env.ts
  apps/ui/app/root.tsx
  apps/ui/app/routes/login.tsx
  apps/ui/app/routes/register.tsx
Labels: enhancement, react/ui

#35 Add a pr template
  .github/pull_request_template.md
Labels: enhancement, maintenance

#44 fixed duplicate server starter
  apps/server/main.go
Labels: go/fiber, maintenance

#49 Fix linting checking in ci
  .github/workflows/ci.yml
Labels: go/fiber, maintenance

#52 Add tests for time handling and coverage report exclusion
  .github/workflows/ci.yml
  .gitignore
  apps/server/tests/lib_test.go
Labels: enhancement, go/fiber, go

#53 Monitoring
  apps/server/api/internal/app.go
  apps/server/api/internal/audit.go
  apps/server/api/internal/auth.go
  apps/server/api/middleware/auth.go
  apps/server/api/routes/app.go
  apps/server/config/config.go
  apps/server/config/logger.go
  apps/server/database/actions.go
  apps/server/lib/constants.go
  apps/server/main.go
  apps/server/migrations/audit_logs.sql
  apps/server/services/audit_service.go
  apps/server/services/auth_service.go
  apps/server/services/cache_service.go
  apps/server/tests/audit_cleanup_test.go
  apps/server/tests/bulk_insert_test.go
  apps/server/types/README.md
  apps/server/types/app.go
  apps/server/types/config.go
  apps/server/types/queries.go
  apps/server/workers/audit_logs.go
Labels: enhancement, go/fiber, go

#55 Formatting and ci fix
  .github/workflows/ci.yml
  apps/server/go.sum
  apps/server/lib/constants.go
Labels: maintenance, go

#58 Add audit_logs migration to create audit_logs table with constraints …
  apps/server/database/migrations/create_audit_logs.sql
Labels: go/fiber, maintenance, go

#68 Updated .env.example
  apps/server/.env.example
Labels: documentation
